apiVersion: apps/v1
kind: Deployment 
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: bensassiahmed/project989:jma-1.1.11-11
          ports:
            - containerPort: 8083 

---

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8083 # The port exposed by the service
      nodePort: 30007 # The port on the node to route traffic to the service
  type: NodePort
