apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: bensassiahmed/project989:jma-1.1.11-11
          ports:
            - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8083
      nodePort: 30007
  type: NodePort
